//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracXFinal.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TeamweDev_GP_Service")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/TeamweDev_GP_Service")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Prod_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prod_Id {
            get {
                return this.Prod_IdField;
            }
            set {
                if ((this.Prod_IdField.Equals(value) != true)) {
                    this.Prod_IdField = value;
                    this.RaisePropertyChanged("Prod_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/TeamweDev_GP_Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrOldPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrCategory {
            get {
                return this.PrCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.PrCategoryField, value) != true)) {
                    this.PrCategoryField = value;
                    this.RaisePropertyChanged("PrCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrDescription {
            get {
                return this.PrDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PrDescriptionField, value) != true)) {
                    this.PrDescriptionField = value;
                    this.RaisePropertyChanged("PrDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrImage {
            get {
                return this.PrImageField;
            }
            set {
                if ((object.ReferenceEquals(this.PrImageField, value) != true)) {
                    this.PrImageField = value;
                    this.RaisePropertyChanged("PrImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrName {
            get {
                return this.PrNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrNameField, value) != true)) {
                    this.PrNameField = value;
                    this.RaisePropertyChanged("PrName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PrOldPrice {
            get {
                return this.PrOldPriceField;
            }
            set {
                if ((this.PrOldPriceField.Equals(value) != true)) {
                    this.PrOldPriceField = value;
                    this.RaisePropertyChanged("PrOldPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrPrice {
            get {
                return this.PrPriceField;
            }
            set {
                if ((this.PrPriceField.Equals(value) != true)) {
                    this.PrPriceField = value;
                    this.RaisePropertyChanged("PrPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrQuantity {
            get {
                return this.PrQuantityField;
            }
            set {
                if ((this.PrQuantityField.Equals(value) != true)) {
                    this.PrQuantityField = value;
                    this.RaisePropertyChanged("PrQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrRating {
            get {
                return this.PrRatingField;
            }
            set {
                if ((this.PrRatingField.Equals(value) != true)) {
                    this.PrRatingField = value;
                    this.RaisePropertyChanged("PrRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrStatus {
            get {
                return this.PrStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PrStatusField, value) != true)) {
                    this.PrStatusField = value;
                    this.RaisePropertyChanged("PrStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/TeamweDev_GP_Service")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Total_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total_ {
            get {
                return this.Total_Field;
            }
            set {
                if ((this.Total_Field.Equals(value) != true)) {
                    this.Total_Field = value;
                    this.RaisePropertyChanged("Total_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        PracXFinal.ServiceReference1.User Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.User> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/register", ReplyAction="http://tempuri.org/IService1/registerResponse")]
        int register(PracXFinal.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/register", ReplyAction="http://tempuri.org/IService1/registerResponse")]
        System.Threading.Tasks.Task<int> registerAsync(PracXFinal.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToCart", ReplyAction="http://tempuri.org/IService1/addToCartResponse")]
        int addToCart(PracXFinal.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToCart", ReplyAction="http://tempuri.org/IService1/addToCartResponse")]
        System.Threading.Tasks.Task<int> addToCartAsync(PracXFinal.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromCart", ReplyAction="http://tempuri.org/IService1/removeFromCartResponse")]
        int removeFromCart(PracXFinal.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromCart", ReplyAction="http://tempuri.org/IService1/removeFromCartResponse")]
        System.Threading.Tasks.Task<int> removeFromCartAsync(PracXFinal.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numItemsInCart", ReplyAction="http://tempuri.org/IService1/numItemsInCartResponse")]
        int numItemsInCart(int u_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numItemsInCart", ReplyAction="http://tempuri.org/IService1/numItemsInCartResponse")]
        System.Threading.Tasks.Task<int> numItemsInCartAsync(int u_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProdsInCart", ReplyAction="http://tempuri.org/IService1/getProdsInCartResponse")]
        PracXFinal.ServiceReference1.Cart[] getProdsInCart(int u_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProdsInCart", ReplyAction="http://tempuri.org/IService1/getProdsInCartResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Cart[]> getProdsInCartAsync(int u_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProduct", ReplyAction="http://tempuri.org/IService1/addProductResponse")]
        int addProduct(PracXFinal.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProduct", ReplyAction="http://tempuri.org/IService1/addProductResponse")]
        System.Threading.Tasks.Task<int> addProductAsync(PracXFinal.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeProduct", ReplyAction="http://tempuri.org/IService1/removeProductResponse")]
        int removeProduct(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeProduct", ReplyAction="http://tempuri.org/IService1/removeProductResponse")]
        System.Threading.Tasks.Task<int> removeProductAsync(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProduct", ReplyAction="http://tempuri.org/IService1/getProductResponse")]
        PracXFinal.ServiceReference1.Product getProduct(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProduct", ReplyAction="http://tempuri.org/IService1/getProductResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product> getProductAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProducts", ReplyAction="http://tempuri.org/IService1/getAllProductsResponse")]
        PracXFinal.ServiceReference1.Product[] getAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProducts", ReplyAction="http://tempuri.org/IService1/getAllProductsResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsAlphabetically", ReplyAction="http://tempuri.org/IService1/getAllProductsAlphabeticallyResponse")]
        PracXFinal.ServiceReference1.Product[] getAllProductsAlphabetically();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsAlphabetically", ReplyAction="http://tempuri.org/IService1/getAllProductsAlphabeticallyResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsAlphabeticallyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsByPrice", ReplyAction="http://tempuri.org/IService1/getAllProductsByPriceResponse")]
        PracXFinal.ServiceReference1.Product[] getAllProductsByPrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsByPrice", ReplyAction="http://tempuri.org/IService1/getAllProductsByPriceResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsByPriceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsPriceFiltered", ReplyAction="http://tempuri.org/IService1/getAllProductsPriceFilteredResponse")]
        PracXFinal.ServiceReference1.Product[] getAllProductsPriceFiltered(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsPriceFiltered", ReplyAction="http://tempuri.org/IService1/getAllProductsPriceFilteredResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsPriceFilteredAsync(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsCategoryFiltered", ReplyAction="http://tempuri.org/IService1/getAllProductsCategoryFilteredResponse")]
        PracXFinal.ServiceReference1.Product[] getAllProductsCategoryFiltered(char aORnORe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllProductsCategoryFiltered", ReplyAction="http://tempuri.org/IService1/getAllProductsCategoryFilteredResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsCategoryFilteredAsync(char aORnORe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllDiscountedProducts", ReplyAction="http://tempuri.org/IService1/getAllDiscountedProductsResponse")]
        PracXFinal.ServiceReference1.Product[] getAllDiscountedProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllDiscountedProducts", ReplyAction="http://tempuri.org/IService1/getAllDiscountedProductsResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllDiscountedProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProduct", ReplyAction="http://tempuri.org/IService1/editProductResponse")]
        int editProduct(PracXFinal.ServiceReference1.Product u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProduct", ReplyAction="http://tempuri.org/IService1/editProductResponse")]
        System.Threading.Tasks.Task<int> editProductAsync(PracXFinal.ServiceReference1.Product u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/purchase", ReplyAction="http://tempuri.org/IService1/purchaseResponse")]
        int purchase(PracXFinal.ServiceReference1.Invoice inv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/purchase", ReplyAction="http://tempuri.org/IService1/purchaseResponse")]
        System.Threading.Tasks.Task<int> purchaseAsync(PracXFinal.ServiceReference1.Invoice inv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/existingInvoices", ReplyAction="http://tempuri.org/IService1/existingInvoicesResponse")]
        PracXFinal.ServiceReference1.Invoice[] existingInvoices(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/existingInvoices", ReplyAction="http://tempuri.org/IService1/existingInvoicesResponse")]
        System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Invoice[]> existingInvoicesAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PracXFinal.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PracXFinal.ServiceReference1.IService1>, PracXFinal.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PracXFinal.ServiceReference1.User Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.User> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public int register(PracXFinal.ServiceReference1.User user) {
            return base.Channel.register(user);
        }
        
        public System.Threading.Tasks.Task<int> registerAsync(PracXFinal.ServiceReference1.User user) {
            return base.Channel.registerAsync(user);
        }
        
        public int addToCart(PracXFinal.ServiceReference1.Cart cart) {
            return base.Channel.addToCart(cart);
        }
        
        public System.Threading.Tasks.Task<int> addToCartAsync(PracXFinal.ServiceReference1.Cart cart) {
            return base.Channel.addToCartAsync(cart);
        }
        
        public int removeFromCart(PracXFinal.ServiceReference1.Cart cart) {
            return base.Channel.removeFromCart(cart);
        }
        
        public System.Threading.Tasks.Task<int> removeFromCartAsync(PracXFinal.ServiceReference1.Cart cart) {
            return base.Channel.removeFromCartAsync(cart);
        }
        
        public int numItemsInCart(int u_Id) {
            return base.Channel.numItemsInCart(u_Id);
        }
        
        public System.Threading.Tasks.Task<int> numItemsInCartAsync(int u_Id) {
            return base.Channel.numItemsInCartAsync(u_Id);
        }
        
        public PracXFinal.ServiceReference1.Cart[] getProdsInCart(int u_id) {
            return base.Channel.getProdsInCart(u_id);
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Cart[]> getProdsInCartAsync(int u_id) {
            return base.Channel.getProdsInCartAsync(u_id);
        }
        
        public int addProduct(PracXFinal.ServiceReference1.Product product) {
            return base.Channel.addProduct(product);
        }
        
        public System.Threading.Tasks.Task<int> addProductAsync(PracXFinal.ServiceReference1.Product product) {
            return base.Channel.addProductAsync(product);
        }
        
        public int removeProduct(int pID) {
            return base.Channel.removeProduct(pID);
        }
        
        public System.Threading.Tasks.Task<int> removeProductAsync(int pID) {
            return base.Channel.removeProductAsync(pID);
        }
        
        public PracXFinal.ServiceReference1.Product getProduct(int ID) {
            return base.Channel.getProduct(ID);
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product> getProductAsync(int ID) {
            return base.Channel.getProductAsync(ID);
        }
        
        public PracXFinal.ServiceReference1.Product[] getAllProducts() {
            return base.Channel.getAllProducts();
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsAsync() {
            return base.Channel.getAllProductsAsync();
        }
        
        public PracXFinal.ServiceReference1.Product[] getAllProductsAlphabetically() {
            return base.Channel.getAllProductsAlphabetically();
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsAlphabeticallyAsync() {
            return base.Channel.getAllProductsAlphabeticallyAsync();
        }
        
        public PracXFinal.ServiceReference1.Product[] getAllProductsByPrice() {
            return base.Channel.getAllProductsByPrice();
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsByPriceAsync() {
            return base.Channel.getAllProductsByPriceAsync();
        }
        
        public PracXFinal.ServiceReference1.Product[] getAllProductsPriceFiltered(int min, int max) {
            return base.Channel.getAllProductsPriceFiltered(min, max);
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsPriceFilteredAsync(int min, int max) {
            return base.Channel.getAllProductsPriceFilteredAsync(min, max);
        }
        
        public PracXFinal.ServiceReference1.Product[] getAllProductsCategoryFiltered(char aORnORe) {
            return base.Channel.getAllProductsCategoryFiltered(aORnORe);
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllProductsCategoryFilteredAsync(char aORnORe) {
            return base.Channel.getAllProductsCategoryFilteredAsync(aORnORe);
        }
        
        public PracXFinal.ServiceReference1.Product[] getAllDiscountedProducts() {
            return base.Channel.getAllDiscountedProducts();
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Product[]> getAllDiscountedProductsAsync() {
            return base.Channel.getAllDiscountedProductsAsync();
        }
        
        public int editProduct(PracXFinal.ServiceReference1.Product u) {
            return base.Channel.editProduct(u);
        }
        
        public System.Threading.Tasks.Task<int> editProductAsync(PracXFinal.ServiceReference1.Product u) {
            return base.Channel.editProductAsync(u);
        }
        
        public int purchase(PracXFinal.ServiceReference1.Invoice inv) {
            return base.Channel.purchase(inv);
        }
        
        public System.Threading.Tasks.Task<int> purchaseAsync(PracXFinal.ServiceReference1.Invoice inv) {
            return base.Channel.purchaseAsync(inv);
        }
        
        public PracXFinal.ServiceReference1.Invoice[] existingInvoices(int id) {
            return base.Channel.existingInvoices(id);
        }
        
        public System.Threading.Tasks.Task<PracXFinal.ServiceReference1.Invoice[]> existingInvoicesAsync(int id) {
            return base.Channel.existingInvoicesAsync(id);
        }
    }
}
